### ISSUE TITLE
How do I declare multiple port expanders ?

### ISSUE THREAD

**Issue by ghost** [glmnet/esphome-components#4]
First of all thank you for the amazing work!
I'm just trying to use multiple arduinos in my port expander config.

Original working sketch contains this snippet

`i2c:
  - id: expander
    sda: GPIO33
    scl:  GPIO32
    scan: true
    frequency: 200kHz

external_components:
  - source: github://glmnet/esphome@ape-external-component
    components: [arduino_port_expander]

arduino_port_expander: 
  id: rioupdx
  address: 0x08
  analog_reference: DEFAULT
  

output:
  - platform: gpio
    pin:
      arduino_port_expander: rioupdx
      number: 9
      mode:
        output: true
        pullup: true 
    id: out_1
    inverted: true

switch:
  - platform: output
    name: Led
    id: led
    output: out_1`

if I try to declare a second board in this way

`i2c:
  - id: expander
    sda: GPIO33
    scl:  GPIO32
    scan: true
    frequency: 200kHz

external_components:
  - source: github://glmnet/esphome@ape-external-component
    components: [arduino_port_expander]

arduino_port_expander: 
  - id: rioupdx
    address: 0x08
    analog_reference: DEFAULT

  - id: rioupsx
    address: 0x09
    analog_reference: DEFAULT  
  

output:
  - platform: gpio
    pin:
      arduino_port_expander: rioupdx
      number: 9
      mode:
        output: true
        pullup: true 
    id: out_1
    inverted: true

switch:
  - platform: output
    name: Led
    id: led
    output: out_1`

The error I get

`INFO ESPHome 2023.12.9
INFO Reading configuration /config/esphome/fuckingsec-terra.yaml...
Failed config

sensor.arduino_port_expander: [source <unicode string>:112]
  
  Too many candidates found for 'arduino_port_expander_id' type 'arduino_port_expander::ArduinoPortExpanderComponent' Some are 'rioupdx', 'rioupsx'.
  platform: arduino_port_expander
  id: updxin8
  pin: A7
  name: RI 8
  device_class: voltage
  state_class: measurement
  accuracy_decimals: 3
  update_interval: 1s
  filters: 
    - debounce: 500ms
  disabled_by_default: False
  force_update: False
  unit_of_measurement: V
sensor.arduino_port_expander: [source <unicode string>:124]
  `

What would be correct way to declare ?

**Comment by glmnet** [comment]
Add 

arduino_port_expander_id: rioupdx

To the sensor component
